before_build:
- nuget restore
after_build:
- nuget pack Core\Suigetsu.Core\Suigetsu.Core.nuspec -Version %appveyor_build_version%
- appveyor PushArtifact Suigetsu.Core.%appveyor_build_version%.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: 1VWw9N4l/dx9R+6jI8NkwAtS5uZZOvtFx78s3o4hUb9+xppT0iEB+Y/FcuVXOzHK
  artifact: /.*\.nupkg/